# 4 Different Ways to Multiply 2 Matrices

Let's establish a simple toy example as a baseline first:

In [1]:
import numpy as np

A = np.array([[1.1, 1.2, 1.3],
              [2.4, 2.5, 2.6],
              [3.7, 3.8, 3.9]])

B = np.array([[4.1, 4.2, 4.3],
              [5.4, 5.5, 5.6],
              [6.7, 6.8, 6.9]])

In [2]:
A @ B

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 1) Compute row-column dot-products (the conventional way)

Each element A[i, j] in the resulting matrix A.B = AB is a dot product of row A[i, ] and column B[, j].

In [3]:
AB = np.zeros((A.shape[0], B.shape[1]))

for i, row in enumerate(A):
    for j, column in enumerate(B.T):
        AB[i, j] = row.dot(column)

AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 2) Row-vectors times matrix

For each column B[, j], compute the dot products between A and B[, j] to get the resulting column AB[, j].

For each row A[i, ], compute the dot products with B to get the resulting row AB[i, ].

In [4]:
AB = np.zeros((A.shape[0], B.shape[1]))

for i, row in enumerate(A):
    AB[i] = row.dot(B)
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 3) Matrix times column-vectors

In [5]:
AB = np.zeros((A.shape[0], B.shape[1]))

for j, column in enumerate(B.T):
    AB[:, j] = A.dot(column[:, None]).flatten()
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 4) Columns times rows

This procedure works for square matrices only:

- Compute the dot-products between the columns in A and rows in B. 
- If A is $m\times n$-dimensional, each dot-product is a $m\times n$-dimensional matrix
- Then sum these matrices

In [6]:
AB = np.zeros((A.shape[1], B.shape[0]))

assert A.shape == B.shape
assert A.shape[0] == A.shape[1]

for column_A, row_B in zip(A.T, B):
    AB += column_A[:, None].dot(row_B[None, :])
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])